# Configuration for H2 Hydrogen Bot
companies:
  - Linde
  - Air Liquide
  - Air Products
  - John Cockerill
  - Siemens Energy
  - NEUMAN & ESSER
  - Sunfire
  - Plug Power
  - Sungrow
  - Peric
  - HiiROC
  - Accelera Cummins
  - Nel ASA
  - Thyssenkrupp Nucera
  - ITM Power
  - Atawey
  - Ivys
  - TOPSOE
  - HydrogenPro
  - Maximator

# Example RSS feeds (you can extend/change)
rss_feeds:
  - https://www.linde.com/en/news/rss.xml
  - https://www.airliquide.com/rss.xml
  - https://www.plugpower.com/feed/
  - https://www.siemens-energy.com/global/en/news/rss.xml

# Keywords / tags to detect (case-insensitive)
keywords:
  - hydrogen
  - h2
  - green hydrogen
  - blue hydrogen
  - electrolyzer
  - electrolyser
  - pem
  - alkaline
  - soec
  - electrolysis
  - fuel cell
  - fcev
  - hrs
  - hydrogen refueling station
  - compression
  - compressor
  - storage
  - ammonia
  - methanol
  - ccus
  - investment
  - fid
  - final investment decision
  - financing
  - offtake
  - power purchase agreement
  - ppa
  - project financing
  - capacity
  - mw
  - gw
  - project
  - projects
  - investments
  - CAPEX
  - ptx
  - power to X
  - p2x
  - pressure swing adsorption
  - PSA
  - purification
  
